import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from  'next/link'
import Pic1 from '../assets/xhome-right.png.pagespeed.ic.9EvmcO3oQb.jpg'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faYoutube, faLinkedin, faGithub, faTwitter, faFacebook, faInstagram, faFacebookMessenger} from '@fortawesome/free-brands-svg-icons';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/220367988-modified.jpg" />
      </Head>
      
      <div className={styles.Body}>
        <div className={styles.intro}>
          <div className={styles.image1}>
            <Image
              src={Pic1}
              alt="Picture of the Owner"
            />
          </div>
          <p className={styles.p1}>HEY THERE..!</p>
          <p className={styles.p2}>I AM CHANDRAKANT</p>
          <p className={styles.p3}>Computer Programer & Software Developer </p>
          <div className={styles.Icons}>
          <div className={styles.icon}>
                            <a href="https://www.instagram.com/" rel="noreferrer" target="_blank">
                                <FontAwesomeIcon className={styles.FontAwesomeIcon}
                                    icon={faInstagram}
                                // style={{  color: "red" }}
                                />
                            </a>
                        </div>
                        <div className={styles.icon}>
                            <a href="https://twitter.com/Chandra17254306" rel="noreferrer" target="_blank">
                                <FontAwesomeIcon className={styles.FontAwesomeIcon}
                                    icon={faTwitter}
                                // style={{  color: "Blue" }}
                                />
                            </a>
                        </div>
                        <div className={styles.icon}>
                            <a href="https://www.facebook.com/" rel="noreferrer" target="_blank">
                                <FontAwesomeIcon className={styles.FontAwesomeIcon}
                                    icon={faFacebook}
                                // style={{  color: "blue" }}
                                />
                            </a>
                        </div>
                        <div className={styles.icon}>
                            <a href="https://www.linkedin.com/" rel="noreferrer" target="_blank">
                                <FontAwesomeIcon className={styles.FontAwesomeIcon}
                                    icon={faLinkedin}
                                //  style={{  color: "blue" }}
                                />
                            </a>
                        </div>
          </div>
          <div className={styles.button1} href="../Component/About.js">See more About me
          </div>
        </div>

        <div>
        </div>



        <div className={styles.box}>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        
      </div>

    </div>
  )
}
